"""Machine-readable tool-validation report per SWGDE 18-Q-001-2.1 §6.

Forensic purpose
----------------
SWGDE 18-Q-001-2.1, "Minimum Requirements for Testing Tools Used in Digital and
Multimedia Forensics" (v2.1, 2024-03-07), §6 "Documentation of Testing Results" says:

    "Results of lab-based testing should be documented. Testing documentation should
    include:
      1. Purpose and scope of testing (identify tool or technique)
      2. Who performed the testing
      3. Date
      4. Testing procedure used or scenarios
      5. Datasets or other testing material used, including expected results
      6. Results and a description of anomalies and their significance
      7. Identified limitations"

That is the whole list — SEVEN fields. This module emits exactly those, plus a small
number of clearly-labelled tool-added fields, and refuses to pretend the tool-added
ones are mandated by 18-Q-001.

Limitations of this module (read before quoting its output)
-----------------------------------------------------------
1. ``conclusion``, ``reviewed_by`` and ``approved`` DO NOT APPEAR in 18-Q-001 §6. They
   are marked ``source="tool-added"`` in :data:`SWGDE_REPORT_FIELDS`; the standard that
   actually governs conclusions and technical review is SWGDE 18-Q-002, "Requirements
   for Report Writing in Digital and Multimedia Forensics" (2018-11-20).
2. ``tool_version`` is not a separate 18-Q-001 field either; §6 folds tool identity into
   field 1 ("identify tool or technique"). Emitting it explicitly is good practice, and
   it is labelled as such rather than as a requirement.
3. Dataset *provenance* is not called out by §6, which says only "datasets or other
   testing material used". Provenance guidance lives in 18-Q-001's reference [1],
   OSAC Digital Evidence, "Guidelines for Data Set Development" (Oct 2022).
4. This module produces a report; it does not confer validity. §5.6 of 18-Q-001 covers
   in-house developed tools and recommends "that the tester be independent of the
   developer". A report generated by the tool about itself does not evidence that
   independence, and :func:`validate_report` always says so in its warnings.
5. SWGDE's redistribution rule is honoured throughout: every quotation carries the
   document number and version/date.

Nothing here ever fabricates a result. :func:`build_report` derives its anomalies and
limitations from the cases it is handed; a report built from failing cases is a report
that says so.
"""

from __future__ import annotations

import html
import json
from dataclasses import dataclass, field
from typing import Any, Optional

from ..models import now_iso

# --- Standards this module quotes ---------------------------------------------
SWGDE_18_Q_001 = (
    "SWGDE 18-Q-001-2.1 (v2.1, 2024-03-07) — Minimum Requirements for Testing "
    "Tools Used in Digital and Multimedia Forensics"
)
SWGDE_18_Q_002 = (
    "SWGDE 18-Q-002 (2018-11-20) — Requirements for Report Writing in Digital "
    "and Multimedia Forensics"
)
SWGDE_12_Q_001 = (
    "SWGDE 12-Q-001 v2.0 (2018-11-20) — Establishing Confidence in Digital and "
    "Multimedia Evidence Forensic Results by Error Mitigation Analysis"
)

#: Companion standards a validation report for this tool should cite.
STANDARDS_CITED: list[str] = [
    SWGDE_18_Q_001,
    SWGDE_12_Q_001,
    SWGDE_18_Q_002,
    (
        "SWGDE 19-Q-001 v2.0 (2021-06-17) — Establishing a Quality Management "
        "System for a Digital and Multimedia Evidence Organization under "
        "ISO/IEC 17025 or 17020"
    ),
    (
        "NIST CFTT — Mobile Device Forensic Tool Specification, Test Assertions "
        "and Test Cases, v3.3 (2025-01)"
    ),
    (
        "OSAC Digital Evidence — Guidelines for Data Set Development (Oct 2022) "
        "[18-Q-001 reference [1]]"
    ),
]

#: SWGDE 12-Q-001 v2.0 primary error types, quoted verbatim. Each anomaly recorded in a
#: report should be classifiable into one of these; the taxonomy is exported so callers
#: can label anomalies consistently instead of inventing ad-hoc categories.
ERROR_TYPES: dict[str, str] = {
    "incompleteness": (
        "All the relevant information has not been acquired or found by the tool."
    ),
    "inaccuracy-existence": "Do all artifacts reported as present actually exist?",
    "inaccuracy-alteration": (
        "Does a forensic tool alter data in a way that changes its meaning?"
    ),
    "inaccuracy-association": (
        "For every set of items identified by a given tool, is each item truly a "
        "part of that set?"
    ),
    "inaccuracy-corruption": (
        "Does the forensic tool detect and compensate for missing and corrupted data?"
    ),
    "misinterpretation": "The results have been incorrectly understood.",
}

#: The three testing types named in 18-Q-001 Appendix A. A report should say which it used.
TESTING_TYPES: dict[str, str] = {
    "known-dataset": (
        "Testing with a Known Dataset — known input, examine output for match or "
        "correct processing."
    ),
    "comparison": (
        "Comparison Testing — two or more tools, check for consistent results. Used "
        "when a known dataset is infeasible; may not catch as many types of errors "
        "as known dataset testing."
    ),
    "empirical": (
        "Empirical Testing — corroborate tool output against other data or manual "
        "verification."
    ),
}


# --- The report field list ----------------------------------------------------
# `source` distinguishes what 18-Q-001 §6 actually requires from what this tool adds.
# `required` drives validate_report(); only genuine §6 obligations are required.
SWGDE_REPORT_FIELDS: list[dict[str, Any]] = [
    {
        "key": "purpose",
        "label": "Purpose of testing",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 1",
    },
    {
        "key": "scope",
        "label": "Scope of testing",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 1",
    },
    {
        "key": "tool_name",
        "label": "Tool or technique under test",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 1 ('identify tool or technique')",
    },
    {
        "key": "tool_version",
        "label": "Tool version",
        "required": True,
        "source": (
            "tool-added; §6 folds tool identity into field 1 and does not name "
            "version as a separate field"
        ),
    },
    {
        "key": "tester",
        "label": "Who performed the testing",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 2",
    },
    {
        "key": "tested_at",
        "label": "Date",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 3",
    },
    {
        "key": "cases",
        "label": "Testing procedure used or scenarios, and results",
        "required": True,
        "source": "18-Q-001-2.1 §6 fields 4 and 6",
    },
    {
        "key": "dataset_name",
        "label": "Datasets or other testing material used",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 5",
    },
    {
        "key": "dataset_provenance",
        "label": "Dataset provenance",
        "required": False,
        "source": (
            "tool-added; §6 field 5 names only the dataset. Provenance guidance is "
            "in 18-Q-001 reference [1], OSAC Guidelines for Data Set Development "
            "(Oct 2022)"
        ),
    },
    {
        "key": "dataset_hash",
        "label": "Dataset hash (SHA-256)",
        "required": False,
        "source": "tool-added; fixes the dataset so the test can be repeated",
    },
    {
        "key": "environment",
        "label": "Test environment",
        "required": False,
        "source": "tool-added; supports re-validation after a version change",
    },
    {
        "key": "anomalies",
        "label": "Anomalies and their significance",
        "required": False,
        "source": (
            "18-Q-001-2.1 §6 field 6. Not marked required because an empty list is "
            "a legitimate result (no anomalies observed); validate_report() warns "
            "instead if a case failed and no anomaly was described"
        ),
    },
    {
        "key": "limitations",
        "label": "Identified limitations",
        "required": True,
        "source": "18-Q-001-2.1 §6 field 7",
    },
    {
        "key": "conclusion",
        "label": "Conclusion",
        "required": False,
        "source": f"tool-added; NOT in 18-Q-001 §6. See {SWGDE_18_Q_002}",
    },
    {
        "key": "reviewed_by",
        "label": "Technical reviewer",
        "required": False,
        "source": f"tool-added; NOT in 18-Q-001 §6. See {SWGDE_18_Q_002}",
    },
    {
        "key": "approved",
        "label": "Approved",
        "required": False,
        "source": f"tool-added; NOT in 18-Q-001 §6. See {SWGDE_18_Q_002}",
    },
]


# --- Records ------------------------------------------------------------------
@dataclass
class ValidationCase:
    """One known-answer scenario: what was expected, what actually happened.

    ``passed`` is a plain boolean recorded by whoever ran the case. Nothing in this
    module ever recomputes it into something more flattering, and ``anomalies`` is
    where the honest description of a failure lives (18-Q-001 §6 field 6).
    """

    case_id: str
    description: str
    artifact_class: str  # e.g. "hashing", "chain-of-custody", "deleted-record recovery"
    expected: dict[str, Any] = field(default_factory=dict)
    actual: dict[str, Any] = field(default_factory=dict)
    passed: bool = False
    anomalies: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "case_id": self.case_id,
            "description": self.description,
            "artifact_class": self.artifact_class,
            "expected": _jsonable(self.expected),
            "actual": _jsonable(self.actual),
            "passed": bool(self.passed),
            "anomalies": list(self.anomalies),
        }


@dataclass
class ValidationReport:
    """A complete 18-Q-001 §6 testing-results record."""

    tool_name: str
    tool_version: str
    tester: str
    tested_at: str
    purpose: str
    scope: str
    dataset_name: str
    dataset_provenance: str
    dataset_hash: str
    environment: dict[str, Any] = field(default_factory=dict)
    cases: list[ValidationCase] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)
    anomalies: list[str] = field(default_factory=list)
    conclusion: str = ""
    reviewed_by: str = ""
    approved: bool = False

    # -- derived counts ------------------------------------------------------
    def passed_count(self) -> int:
        return sum(1 for c in self.cases if c.passed)

    def failed_count(self) -> int:
        return sum(1 for c in self.cases if not c.passed)

    def to_dict(self) -> dict[str, Any]:
        return {
            "standard": SWGDE_18_Q_001,
            "standards_cited": list(STANDARDS_CITED),
            "field_definitions": [dict(f) for f in SWGDE_REPORT_FIELDS],
            "tool_name": self.tool_name,
            "tool_version": self.tool_version,
            "tester": self.tester,
            "tested_at": self.tested_at,
            "purpose": self.purpose,
            "scope": self.scope,
            "dataset_name": self.dataset_name,
            "dataset_provenance": self.dataset_provenance,
            "dataset_hash": self.dataset_hash,
            "environment": _jsonable(self.environment),
            "cases": [c.to_dict() for c in self.cases],
            "case_count": len(self.cases),
            "passed_count": self.passed_count(),
            "failed_count": self.failed_count(),
            "limitations": list(self.limitations),
            "anomalies": list(self.anomalies),
            "conclusion": self.conclusion,
            "reviewed_by": self.reviewed_by,
            "approved": bool(self.approved),
            "error_types": dict(ERROR_TYPES),
            "testing_types": dict(TESTING_TYPES),
        }


def _jsonable(value: Any) -> Any:
    """Coerce a value into something ``json.dumps`` will accept, without inventing data.

    Anything unserialisable becomes its ``repr()`` — visibly a repr, so nobody mistakes
    it for structured data that was really there.
    """
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, bytes):
        # Never guess an encoding for evidence bytes; show them unambiguously.
        return {"__bytes_hex__": value.hex(), "length": len(value)}
    return repr(value)


# --- The standing disclosures -------------------------------------------------
def known_limitations() -> list[str]:
    """The verified dead-ends this tool must disclose in EVERY validation report.

    These are not hypothetical risks; each is a hard boundary confirmed against Android
    platform behaviour. They go into 18-Q-001 §6 field 7 ("Identified limitations")
    unconditionally, because omitting them would let a reader infer capabilities the
    tool does not have.
    """
    return [
        (
            "No write-blocking exists for mobile devices. There is no hardware or "
            "software write-blocker for a live Android device (SWGDE 18-F-003). Device "
            "state is recorded and every altering action is logged with "
            "alters_device=True; it is not prevented. Any claim that this tool is "
            "'read-only' would be false."
        ),
        (
            "No unallocated-space or file-slack recovery is performed, and on Android "
            "10+ with file-based encryption (FBE) none is possible: freed blocks outside "
            "a decrypted file's extent are ciphertext, so there is nothing meaningful to "
            "carve. Recovery is confined to the interior of individual SQLite database "
            "files."
        ),
        (
            "No deleted-record recovery is possible on a non-rooted device. Content "
            "providers (SMS, call log, contacts, calendar) return live rows only; the "
            "underlying database files sit in app-private storage that a non-root "
            "helper APK cannot read. Absence of a deleted record in a non-root "
            "extraction is evidence of nothing."
        ),
        (
            "Root is not decryption. On a device in the Before-First-Unlock (BFU) state "
            "the credential-encrypted (CE) storage keys are not in memory, so CE data is "
            "inaccessible even with root. 'Present but encrypted / inaccessible' is "
            "reported as exactly that, and is never collapsed into 'not found'."
        ),
        (
            "Application content protected by SQLCipher with a hardware-Keystore-wrapped "
            "key is not recoverable at any tier. This includes Signal, Threema, Session "
            "and Wickr. The key never leaves the TEE/StrongBox, so the ciphertext cannot "
            "be decrypted off-device regardless of root."
        ),
        (
            "Android framework SQLite databases are built with SECURE_DELETE and "
            "AUTOVACUUM enabled. Freed pages are zeroed and returned to the operating "
            "system, so the freelist yield from telephony, contacts and call-log "
            "databases is near zero. A nil recovery result from these databases is the "
            "expected outcome and must not be read as proof that nothing was deleted."
        ),
        (
            "No characterised error rate has been established for this tool. Per SWGDE "
            "12-Q-001 v2.0, digital forensics is far more prone to systematic than "
            "random errors, so confidence rests on error mitigation analysis — known "
            "limitations, quality control, and corroboration — rather than on a "
            "statistical error rate. No error rate should be quoted from this report "
            "because none has been measured."
        ),
        (
            "This tool performs a logical acquisition only. It creates no device image, "
            "performs no physical or chip-off acquisition, and has no image-file ingest "
            "mode. Findings are a field-triage preview and are not a substitute for a "
            "full laboratory examination (NIST SP 800-101r1 §4.5)."
        ),
        (
            "As an in-house developed tool (18-Q-001-2.1 §5.6), re-testing is required "
            "'At first use and all tool revisions', and §5.6 recommends 'that the tester "
            "be independent of the developer'. A report generated by the tool about "
            "itself does not satisfy that recommendation."
        ),
    ]


DEFAULT_PURPOSE = (
    "Establish, by known-answer testing, whether the eRakshak triage engine performs "
    "as expected for its core evidential functions — cryptographic hashing, "
    "chain-of-custody manifest integrity verification, deleted-record recovery from "
    "SQLite, and timestamp normalisation — and to document the limitations of those "
    "functions (18-Q-001-2.1 §1: 'to evaluate whether a tool or procedure performs as "
    "expected and to understand the limitations of tools')."
)

DEFAULT_SCOPE = (
    "Scope is limited to offline, lab-based known-answer testing (18-Q-001-2.1 "
    "Appendix A, testing type 1) of the Python engine against programmatically "
    "generated ground-truth fixtures. NOT in scope: acquisition from a physical "
    "device, any Tier-1 helper-APK or Tier-2 root path, application-specific parsers, "
    "processing speed, ease of use, interpretive analysis, and examiner competency "
    "(18-Q-001-2.1 §3 excludes the last four from tool testing in any case). Results "
    "are scoped to the specific dataset named in this report and assert nothing about "
    "completeness on real device data."
)


def build_report(
    cases: list[ValidationCase],
    *,
    tool_name: str,
    tool_version: str,
    tester: str = "",
    dataset_name: str = "",
    dataset_provenance: str = "",
    dataset_hash: str = "",
    environment: Optional[dict[str, Any]] = None,
    purpose: str = "",
    scope: str = "",
) -> ValidationReport:
    """Assemble a :class:`ValidationReport` from executed cases.

    Anomalies (§6 field 6) and limitations (§6 field 7) are DERIVED from the cases —
    they are not accepted as parameters — so a report cannot be built that claims a
    clean run over failing cases. ``tester`` and ``dataset_name`` deliberately default
    to empty: an unattributed report must fail :func:`validate_report`, not quietly
    acquire a plausible-looking author.
    """
    anomalies: list[str] = []
    seen: set[str] = set()
    for case in cases:
        for anomaly in case.anomalies:
            text = f"[{case.case_id}] {anomaly}"
            if text not in seen:
                seen.add(text)
                anomalies.append(text)

    limitations = list(known_limitations())
    for case in cases:
        if not case.passed:
            limitations.append(
                f"[{case.case_id}] Case did not produce the expected result; the "
                f"capability it covers ({case.artifact_class}) is not demonstrated by "
                "this report and must not be relied on until re-tested."
            )

    report = ValidationReport(
        tool_name=tool_name,
        tool_version=tool_version,
        tester=tester,
        tested_at=now_iso(),
        purpose=purpose or DEFAULT_PURPOSE,
        scope=scope or DEFAULT_SCOPE,
        dataset_name=dataset_name,
        dataset_provenance=dataset_provenance,
        dataset_hash=dataset_hash,
        environment=dict(environment or {}),
        cases=list(cases),
        limitations=limitations,
        anomalies=anomalies,
        conclusion="",
    )
    report.conclusion = _build_conclusion(report)
    return report


def _build_conclusion(report: ValidationReport) -> str:
    """Generate the (tool-added, NOT 18-Q-001-mandated) conclusion from the results.

    Generated rather than hand-written so it can never contradict the case table.
    """
    total = len(report.cases)
    passed = report.passed_count()
    failed = report.failed_count()
    failed_ids = [c.case_id for c in report.cases if not c.passed]

    verdict = (
        "performed as expected for every case in this dataset"
        if failed == 0
        else "did NOT perform as expected for every case in this dataset"
    )

    return (
        f"{report.tool_name} {report.tool_version} was tested with a known dataset "
        f"(18-Q-001-2.1 Appendix A, testing type 1) over {total} case(s): {passed} "
        f"produced the expected result, {failed} did not. The tool {verdict}. "
        + (
            f"Cases not producing the expected result: {', '.join(failed_ids)}. "
            if failed_ids
            else ""
        )
        + "Per 18-Q-001-2.1 §4, 'Testing is not necessarily pass/fail' — this result "
        "is a statement about the named dataset only and asserts nothing about "
        "completeness on real device data. All standing limitations in the "
        "'Identified limitations' field apply in full and are not superseded by a "
        "passing result. This conclusion field is tool-added: SWGDE 18-Q-001-2.1 §6 "
        f"does not require a conclusion; see {SWGDE_18_Q_002} for report-level "
        "requirements."
    )


def validate_report(report: ValidationReport) -> dict[str, Any]:
    """Check a report against :data:`SWGDE_REPORT_FIELDS`.

    Returns ``{"complete": bool, "missing_required": [...], "warnings": [...]}``.
    ``complete`` means only that every required §6 field is populated. It is NOT a
    statement that the tool is validated, and the warnings list says so where relevant.
    """
    data = report.to_dict()
    missing: list[str] = []
    warnings: list[str] = []

    for spec in SWGDE_REPORT_FIELDS:
        if not spec["required"]:
            continue
        value = data.get(spec["key"])
        empty = value is None or (
            isinstance(value, (str, list, dict, tuple)) and len(value) == 0
        )
        if empty:
            missing.append(spec["key"])

    if not report.dataset_provenance:
        warnings.append(
            "dataset_provenance is empty. 18-Q-001-2.1 reference [1] (OSAC Guidelines "
            "for Data Set Development, Oct 2022) governs dataset provenance; without it "
            "the dataset cannot be independently obtained or evaluated."
        )
    if not report.dataset_hash:
        warnings.append(
            "dataset_hash is empty. Without a fixed dataset digest this test is not "
            "reproducible by a third party."
        )
    if report.failed_count() and not report.anomalies:
        warnings.append(
            f"{report.failed_count()} case(s) did not produce the expected result but "
            "no anomaly was described. 18-Q-001-2.1 §6 field 6 requires 'Results and a "
            "description of anomalies and their significance'."
        )
    if not report.conclusion:
        warnings.append(
            f"conclusion is empty. Not required by 18-Q-001-2.1 §6, but {SWGDE_18_Q_002} "
            "governs report conclusions."
        )
    if not report.reviewed_by:
        warnings.append(
            f"reviewed_by is empty: no technical review is evidenced. See {SWGDE_18_Q_002}. "
            "Technical/peer review is also named as a quality-control mitigation in "
            f"{SWGDE_12_Q_001}."
        )
    if not report.approved:
        warnings.append(
            "approved is False: this report has not been approved. Treat it as a "
            "working record, not an authorised validation."
        )
    if not report.cases:
        warnings.append(
            "No test cases are recorded. A report with no cases documents no testing "
            "whatsoever and must not be cited as evidence of validation."
        )
    # Standing warning — always true for a self-generated report, so always emitted.
    warnings.append(
        "SWGDE 18-Q-001-2.1 §5.6 (in-house developed tools): 'it is recommended that "
        "the tester be independent of the developer'. This report does not evidence "
        "tester independence, and a report generated by the tool about itself cannot."
    )

    return {
        "complete": len(missing) == 0,
        "missing_required": missing,
        "warnings": warnings,
    }


def render_report_json(report: ValidationReport) -> str:
    """The machine-readable artifact: the whole report as indented JSON."""
    payload = report.to_dict()
    payload["validation"] = validate_report(report)
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)


def render_report_html(report: ValidationReport) -> str:
    """Render the report as a fully escaped, self-contained HTML fragment.

    Every interpolated value is passed through :func:`html.escape`; case descriptions
    and anomaly text can contain arbitrary characters carved out of evidence, so none
    of it is ever trusted as markup.
    """
    esc = html.escape
    data = report.to_dict()
    checks = validate_report(report)
    parts: list[str] = []

    parts.append('<section class="swgde-validation-report">')
    parts.append("<h2>Tool validation report</h2>")
    parts.append("<p class='standard'>Documented per {}</p>".format(esc(SWGDE_18_Q_001)))

    # -- §6 fields -----------------------------------------------------------
    parts.append("<table class='fields'><tbody>")
    scalar_keys = {
        "purpose",
        "scope",
        "tool_name",
        "tool_version",
        "tester",
        "tested_at",
        "dataset_name",
        "dataset_provenance",
        "dataset_hash",
        "conclusion",
        "reviewed_by",
    }
    for spec in SWGDE_REPORT_FIELDS:
        key = spec["key"]
        if key not in scalar_keys:
            continue
        value = data.get(key) or ""
        flag = "required" if spec["required"] else "optional"
        parts.append(
            "<tr><th>{label}</th><td>{value}</td>"
            "<td class='src'>{flag} &mdash; {src}</td></tr>".format(
                label=esc(spec["label"]),
                value=esc(str(value)) if value else "<em>(not supplied)</em>",
                flag=esc(flag),
                src=esc(str(spec["source"])),
            )
        )
    parts.append(
        "<tr><th>Approved</th><td>{}</td><td class='src'>optional &mdash; "
        "tool-added</td></tr>".format("yes" if report.approved else "no")
    )
    parts.append("</tbody></table>")

    # -- environment ---------------------------------------------------------
    if report.environment:
        parts.append("<h3>Test environment</h3><ul>")
        for k, v in sorted(report.environment.items()):
            parts.append(
                "<li>{}: {}</li>".format(esc(str(k)), esc(str(_jsonable(v))))
            )
        parts.append("</ul>")

    # -- cases ---------------------------------------------------------------
    parts.append(
        "<h3>Testing procedure / scenarios and results ({p} of {t} produced the "
        "expected result)</h3>".format(p=report.passed_count(), t=len(report.cases))
    )
    parts.append(
        "<table class='cases'><thead><tr>"
        "<th>Case</th><th>Artifact class</th><th>Description</th>"
        "<th>Expected</th><th>Actual</th><th>Result</th><th>Anomalies</th>"
        "</tr></thead><tbody>"
    )
    for case in report.cases:
        d = case.to_dict()
        parts.append(
            "<tr class='{cls}'><td>{cid}</td><td>{ac}</td><td>{desc}</td>"
            "<td><pre>{exp}</pre></td><td><pre>{act}</pre></td>"
            "<td>{res}</td><td>{anom}</td></tr>".format(
                cls="passed" if case.passed else "failed",
                cid=esc(case.case_id),
                ac=esc(case.artifact_class),
                desc=esc(case.description),
                exp=esc(json.dumps(d["expected"], indent=1, ensure_ascii=False)),
                act=esc(json.dumps(d["actual"], indent=1, ensure_ascii=False)),
                res="as expected" if case.passed else "NOT as expected",
                anom=(
                    "<br>".join(esc(a) for a in case.anomalies)
                    if case.anomalies
                    else "&mdash;"
                ),
            )
        )
    parts.append("</tbody></table>")

    # -- anomalies -----------------------------------------------------------
    parts.append("<h3>Anomalies and their significance</h3>")
    if report.anomalies:
        parts.append("<ul>")
        parts.extend("<li>{}</li>".format(esc(a)) for a in report.anomalies)
        parts.append("</ul>")
    else:
        parts.append("<p>No anomalies were observed over the cases in this dataset.</p>")

    # -- limitations ---------------------------------------------------------
    parts.append("<h3>Identified limitations</h3><ul>")
    parts.extend("<li>{}</li>".format(esc(lim)) for lim in report.limitations)
    parts.append("</ul>")

    # -- completeness --------------------------------------------------------
    parts.append("<h3>Report completeness check</h3>")
    parts.append(
        "<p>Required 18-Q-001-2.1 §6 fields populated: {}</p>".format(
            "yes" if checks["complete"] else "NO"
        )
    )
    if checks["missing_required"]:
        parts.append(
            "<p class='missing'>Missing required fields: {}</p>".format(
                esc(", ".join(checks["missing_required"]))
            )
        )
    parts.append("<ul class='warnings'>")
    parts.extend("<li>{}</li>".format(esc(w)) for w in checks["warnings"])
    parts.append("</ul>")

    # -- citations -----------------------------------------------------------
    parts.append("<h3>Standards cited</h3><ul>")
    parts.extend("<li>{}</li>".format(esc(s)) for s in STANDARDS_CITED)
    parts.append("</ul>")
    parts.append("</section>")
    return "\n".join(parts)
