/**
 * ReportView — Triage Report Generation & Preview
 *
 * Embeds the self-contained HTML report (generated by engine/triage/report.py)
 * in an iframe for instant review, and exposes:
 *
 *   • "Generate / Regenerate Report" — calls POST /api/case/{id}/report/regenerate
 *     which rebuilds report.html from the current case data on demand.
 *   • "Open in New Tab" — opens the raw HTML for full-page reading.
 *   • "Download PDF" — uses the Electron PDF renderer (via window.erakshak IPC)
 *     when running inside the packaged app; falls back to window.print() in the
 *     browser dev environment.
 *
 * State machine:
 *   checking → (report exists)  → loaded
 *           → (report missing)  → not-generated
 *   generating → success → loaded
 *             → error   → error
 */
import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api";
import { SectionHeader } from "../components/common";

type ViewState =
  | { kind: "checking" }
  | { kind: "not-generated" }
  | { kind: "generating" }
  | { kind: "loaded" }
  | { kind: "error"; message: string };

export function ReportView({ caseId }: { caseId: string }) {
  const reportUrl = api.reportUrl(caseId);
  const [state, setState] = useState<ViewState>({ kind: "checking" });
  const [pdfBusy, setPdfBusy] = useState(false);
  const [pdfMsg, setPdfMsg] = useState<string | null>(null);

  // On mount, probe the report endpoint to decide which UI to show.
  const probe = useCallback(async () => {
    setState({ kind: "checking" });
    try {
      const res = await fetch(reportUrl);
      if (res.ok) {
        setState({ kind: "loaded" });
      } else if (res.status === 404) {
        setState({ kind: "not-generated" });
      } else {
        setState({ kind: "error", message: `Server returned HTTP ${res.status}` });
      }
    } catch (e) {
      setState({ kind: "error", message: "Could not reach the engine — is it running?" });
    }
  }, [reportUrl]);

  useEffect(() => { probe(); }, [probe]);

  async function generate() {
    setState({ kind: "generating" });
    try {
      await api.regenerateReport(caseId);
      setState({ kind: "loaded" });
    } catch (e) {
      setState({
        kind: "error",
        message: e instanceof Error ? e.message : "Report generation failed",
      });
    }
  }

  async function downloadPdf() {
    setPdfBusy(true);
    setPdfMsg(null);
    try {
      // Electron path: IPC → Chromium headless render → PDF preview window.
      if (typeof window !== "undefined" && (window as any).erakshak?.exportAndPreviewReport) {
        await (window as any).erakshak.exportAndPreviewReport(caseId);
        setPdfMsg("PDF preview opened.");
      } else {
        // Browser dev fallback: open the report in a new tab and trigger print dialog.
        const win = window.open(reportUrl, "_blank");
        if (win) {
          win.addEventListener("load", () => {
            win.focus();
            win.print();
          });
          setPdfMsg("Print dialog opened — save as PDF.");
        } else {
          setPdfMsg("Pop-up blocked. Please allow pop-ups and try again.");
        }
      }
    } catch (e) {
      setPdfMsg(e instanceof Error ? e.message : "PDF export failed");
    } finally {
      setPdfBusy(false);
    }
  }

  // ---- Action buttons row (reused in multiple states) ----
  const ActionsRow = (
    <div className="flex items-center gap-2 flex-wrap">
      <button
        id="btn-generate-report"
        className="btn-accent text-sm"
        onClick={generate}
        disabled={state.kind === "generating"}
      >
        {state.kind === "generating" ? (
          <span className="flex items-center gap-1.5">
            <svg className="animate-spin h-3.5 w-3.5" viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" className="opacity-25"/>
              <path fill="currentColor" className="opacity-75"
                d="M4 12a8 8 0 018-8v8z"/>
            </svg>
            Generating…
          </span>
        ) : state.kind === "loaded" ? "Regenerate Report" : "Generate Report"}
      </button>

      {state.kind === "loaded" && (
        <>
          <a
            id="btn-open-report-tab"
            className="btn-ghost text-sm"
            href={reportUrl}
            target="_blank"
            rel="noreferrer"
          >
            Open in New Tab ↗
          </a>
          <button
            id="btn-download-pdf"
            className="btn-ghost text-sm"
            onClick={downloadPdf}
            disabled={pdfBusy}
          >
            {pdfBusy ? "Exporting…" : "⬇ Download PDF"}
          </button>
        </>
      )}

      {pdfMsg && (
        <span className="text-xs text-muted">{pdfMsg}</span>
      )}
    </div>
  );

  return (
    <div className="p-6 h-full flex flex-col">
      <SectionHeader
        title="Triage Report"
        sub="NIST/SWGDE-aligned HTML report with Section 65B certificate block — printable to PDF"
        right={ActionsRow}
      />

      {/* ---- State-specific body ---- */}
      {state.kind === "checking" && (
        <div className="flex items-center justify-center flex-1 text-muted text-sm">
          Checking report status…
        </div>
      )}

      {state.kind === "not-generated" && (
        <div className="card flex flex-col items-center justify-center flex-1 gap-4 text-center px-8 py-12">
          <div className="text-5xl">📄</div>
          <div>
            <p className="text-ink font-semibold text-base">Report not yet generated</p>
            <p className="text-muted text-sm mt-1 max-w-sm">
              Click <strong>Generate Report</strong> to build the self-contained HTML report
              with NIST/SWGDE fields, confidence badges, audit log, and Section 65B certificate.
            </p>
          </div>
          <button
            id="btn-generate-report-center"
            className="btn-accent"
            onClick={generate}
          >
            Generate Report
          </button>
        </div>
      )}

      {state.kind === "generating" && (
        <div className="card flex flex-col items-center justify-center flex-1 gap-3 text-center">
          <svg className="animate-spin h-8 w-8 text-accent" viewBox="0 0 24 24" fill="none">
            <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" className="opacity-25"/>
            <path fill="currentColor" className="opacity-75" d="M4 12a8 8 0 018-8v8z"/>
          </svg>
          <p className="text-muted text-sm">Building report…</p>
        </div>
      )}

      {state.kind === "error" && (
        <div className="card flex flex-col items-center justify-center flex-1 gap-3 text-center px-8">
          <div className="text-3xl">⚠️</div>
          <p className="text-ink font-medium">Report generation failed</p>
          <p className="text-muted text-sm font-mono bg-panel-2 px-3 py-2 rounded">
            {state.message}
          </p>
          <button className="btn-ghost text-sm mt-2" onClick={generate}>
            Retry
          </button>
        </div>
      )}

      {state.kind === "loaded" && (
        <div className="card overflow-hidden flex-1 min-h-0">
          <iframe
            id="iframe-triage-report"
            src={reportUrl}
            title="eRakshak Triage Report"
            className="w-full h-full bg-white border-0"
            onError={() =>
              setState({ kind: "error", message: "Failed to load the report iframe." })
            }
          />
        </div>
      )}
    </div>
  );
}
