"""IEEE OUI (MAC vendor prefix) lookup — offline, snapshot-versioned.

Forensic purpose
----------------
The first three octets of an IEEE-802 EUI-48 address are the Organisationally
Unique Identifier (OUI) assigned by the IEEE Registration Authority.  For a
*public* Bluetooth device address this lets us name the party that registered
the address block, which is often the only vendor attribution available for a
peer device whose friendly ``Name`` is peer-supplied (and therefore unverified).

Limitations — read these before quoting a result in a report
------------------------------------------------------------
* An OUI identifies the **registered assignee of the address block**, i.e. the
  silicon / module vendor or the company that bought the block.  It is NOT
  proof of the brand printed on the product.  Results are phrased as
  "registered assignee of OUI xx:xx:xx".
* Lookup is only meaningful for **public** addresses.  A Bluetooth LE *random*
  address (``AddrType`` 1 or 3) is generated by the peer and carries no
  registry meaning whatsoever — :func:`lookup_vendor` refuses those and
  returns ``None``.  Reporting "Apple, Inc." because a random address happens
  to fall inside a registered range is a fabricated finding.
* A **locally administered** address (bit 1 of the first octet set) is by
  definition not in the IEEE registry — lookup is refused.
* This table is a **pruned subset** of the IEEE MA-L registry, not the whole
  registry.  ``None`` therefore means "not in this offline subset", NOT
  "unassigned prefix".  Never report an unresolved OUI as "unknown vendor" —
  report it as "not resolvable from the offline table shipped with this tool".
* MA-M (28-bit) and MA-S (36-bit) sub-assignments are deliberately NOT loaded.
  Resolving one of those against its MA-L parent block would name the wrong
  company, so we only ever claim "IEEE MA-L assignee".

Every entry below was taken verbatim from the IEEE MA-L registry
(https://standards-oui.ieee.org/oui/oui.csv) at the snapshot date recorded in
:data:`OUI_REGISTRY_SNAPSHOT`.  No prefix in this file was invented.
"""

from __future__ import annotations

import re
from typing import Optional

# Date the IEEE MA-L registry was retrieved to build OUI_TABLE.  Printed in the
# report so a lookup is reproducible: OUI assignments change over time and an
# unversioned lookup cannot be audited.
OUI_REGISTRY_SNAPSHOT = "2026-08-01"
OUI_REGISTRY_NAME = "IEEE MA-L"
OUI_REGISTRY_URL = "https://standards-oui.ieee.org/oui/oui.csv"

# Vendors that matter for Bluetooth triage but have **no MA-L assignment** of
# their own (they ship modules built on someone else's silicon, or use MA-M/MA-S
# sub-blocks we deliberately do not load).  Recorded here so the absence is an
# explained fact rather than a silent gap.
NO_MAL_ASSIGNMENT_NOTE = (
    "Some consumer Bluetooth brands (e.g. Anker/Soundcore, Tile, Noise/Nexxbase, "
    "Bluetrum-based earbuds) hold no IEEE MA-L block of their own; their devices "
    "carry the OUI of the module or silicon vendor instead. An unresolved or "
    "silicon-vendor result is expected for those and must not be reported as the "
    "product brand."
)

_MAC_SEP_RE = re.compile(r"[:\-\.\s]")
_HEX12_RE = re.compile(r"^[0-9A-F]{12}$")


# ---------------------------------------------------------------------------
# Offline IEEE MA-L subset (verbatim assignee names, snapshot above)
# ---------------------------------------------------------------------------

OUI_TABLE: dict[str, str] = {
    "0000F0": "Samsung Electronics Co., Ltd",
    "00014A": "Sony Corporation",
    "0001A9": "BMW AG",
    "0001E6": "Hewlett Packard",
    "0001E7": "Hewlett Packard",
    "000389": "Plantronics, Inc.",
    "000393": "Apple, Inc.",
    "0003FF": "Microsoft Corporation",
    "0004F2": "Polycom",
    "000502": "Apple, Inc.",
    "000512": "Zebra Technologies Inc.",
    "00054F": "Garmin International",
    "00065B": "Dell Inc.",
    "0007A4": "GN Netcom A/S (Jabra)",
    "0007AB": "Samsung Electronics Co., Ltd",
    "000874": "Dell Inc.",
    "0009BF": "Nintendo Co., Ltd",
    "000A00": "MediaTek Inc",
    "000A08": "Alps Alpine",
    "000A27": "Apple, Inc.",
    "000A95": "Apple, Inc.",
    "000AD9": "Sony Corporation",
    "000B57": "Silicon Laboratories",
    "000C43": "MediaTek Inc",
    "000C8A": "Bose Corporation",
    "000CE7": "MediaTek Inc",
    "000D4B": "Roku, Inc.",
    "000D5C": "Robert Bosch GmbH",
    "000D93": "Apple, Inc.",
    "000E07": "Sony Corporation",
    "000E58": "Sonos, Inc.",
    "000E6D": "Murata Manufacturing Co., Ltd.",
    "000EDD": "Shure Incorporated",
    "000FDE": "Sony Corporation",
    "0010FA": "Apple, Inc.",
    "001124": "Apple, Inc.",
    "001237": "Texas Instruments",
    "001247": "Samsung Electronics Co., Ltd",
    "00124B": "Texas Instruments",
    "00125A": "Microsoft Corporation",
    "0012D1": "Texas Instruments",
    "0012D2": "Texas Instruments",
    "0012F0": "Intel Corporate",
    "0012FB": "Samsung Electronics Co., Ltd",
    "001302": "Intel Corporate",
    "001320": "Intel Corporate",
    "001377": "Samsung Electronics Co., Ltd",
    "0013CE": "Intel Corporate",
    "0013E0": "Murata Manufacturing Co., Ltd.",
    "001451": "Apple, Inc.",
    "00152A": "Nokia Corporation",
    "00155D": "Microsoft Corporation",
    "001570": "Zebra Technologies Inc.",
    "001599": "Samsung Electronics Co., Ltd",
    "0015B9": "Samsung Electronics Co., Ltd",
    "001632": "Samsung Electronics Co., Ltd",
    "001656": "Nintendo Co., Ltd",
    "00165A": "Harman Specialty Group",
    "001694": "Sennheiser Communications A/S",
    "0017AB": "Nintendo Co., Ltd",
    "0017FA": "Microsoft Corporation",
    "001882": "Huawei Technologies Co., Ltd",
    "00192D": "Nokia Corporation",
    "00197F": "Plantronics, Inc.",
    "001A11": "Google, Inc.",
    "001B66": "Sennheiser electronic GmbH & Co. KG",
    "001C62": "LG Electronics",
    "001CD7": "Harman/Becker Automotive Systems GmbH",
    "001E10": "Huawei Technologies Co., Ltd",
    "001E75": "LG Electronics",
    "001F20": "Logitech",
    "001F6B": "LG Electronics",
    "001FE3": "LG Electronics",
    "0021E8": "Murata Manufacturing Co., Ltd.",
    "0022D0": "Polar Electro Oy",
    "0024E4": "Withings",
    "002568": "Huawei Technologies Co., Ltd",
    "00259E": "Huawei Technologies Co., Ltd",
    "0026B4": "Ford Motor Company",
    "0026E8": "Murata Manufacturing Co., Ltd.",
    "002EC7": "Huawei Technologies Co., Ltd",
    "003C84": "Silicon Laboratories",
    "004B12": "Espressif Inc.",
    "005043": "Marvell Semiconductor, Inc.",
    "006034": "Robert Bosch GmbH",
    "006201": "Motorola Mobility LLC",
    "00620B": "Broadcom",
    "0068EB": "HP Inc.",
    "007007": "Espressif Inc.",
    "007147": "Amazon Technologies Inc.",
    "0076B6": "Ford Motor Company",
    "007DFA": "Volkswagen Group of America",
    "008621": "Amazon Technologies Inc.",
    "009CC0": "vivo Mobile Communication Co., Ltd.",
    "009EC8": "Xiaomi Communications Co Ltd",
    "00A050": "Cypress Semiconductor",
    "00A0C6": "Qualcomm Inc.",
    "00A0DE": "Yamaha Corporation",
    "00B810": "Yichip Microelectronics (Hangzhou) Co., Ltd",
    "00B8B6": "Motorola Mobility LLC",
    "00BB3A": "Amazon Technologies Inc.",
    "00BE44": "Silicon Laboratories",
    "00C059": "DENSO Corporation",
    "00C30A": "Xiaomi Communications Co Ltd",
    "00CAE0": "Guangdong Oppo Mobile Telecommunications Corp., Ltd",
    "00E036": "Pioneer Corporation",
    "00E04C": "Realtek Semiconductor Corp.",
    "00EC0A": "Xiaomi Communications Co Ltd",
    "00F361": "Amazon Technologies Inc.",
    "00F620": "Google, Inc.",
    "00FADE": "Motorola Mobility LLC",
    "04006E": "Google, Inc.",
    "040E3C": "HP Inc.",
    "04106B": "Xiaomi Communications Co Ltd",
    "041FB8": "vivo Mobile Communication Co., Ltd.",
    "042405": "Guangdong Oppo Mobile Telecommunications Corp., Ltd",
    "043201": "Broadcom",
    "044169": "GoPro",
    "0452C7": "Bose Corporation",
    "045747": "GoPro",
    "046761": "Beijing Xiaomi Mobile Software Co., Ltd",
    "047F0E": "Barrot Technology Co., Ltd.",
    "048308": "Espressif Inc.",
    "0488E2": "Beats Electronics LLC",
    "04A85A": "SZ DJI Technology Co., Ltd",
    "04AE47": "Beijing Xiaomi Mobile Software Co., Ltd",
    "04B167": "Xiaomi Communications Co Ltd",
    "04B247": "Espressif Inc.",
    "04C8B0": "Google, Inc.",
    "04DBD9": "Guangdong Oppo Mobile Telecommunications Corp., Ltd",
    "080581": "Roku, Inc.",
    "0823B2": "vivo Mobile Communication Co., Ltd.",
    "084ACF": "Guangdong Oppo Mobile Telecommunications Corp., Ltd",
    "087F98": "vivo Mobile Communication Co., Ltd.",
    "088BC8": "Google, Inc.",
    "08B8D0": "Chipsea Technologies (Shenzhen) Corp.",
    "08C8C2": "GN Audio A/S (Jabra)",
    "08DF1F": "Bose Corporation",
    "08F0B6": "Edifier International",
    "0C01C8": "DENSO Corporation",
    "0C298F": "Tesla, Inc.",
    "0C659A": "Panasonic Automotive Systems Co., Ltd",
    "0C7E24": "Garmin International",
    "0C8CDC": "Suunto Oy",
    "0C9043": "Realme Chongqing Mobile Telecommunications Corp., Ltd",
    "0C9541": "Chipsea Technologies (Shenzhen) Corp.",
    "0C9AE6": "SZ DJI Technology Co., Ltd",
    "0CAEBD": "Edifier International",
    "0CE67C": "Realme Chongqing Mobile Telecommunications Corp., Ltd",
    "0CFC83": "Airoha Technology Corp.",
    "101849": "Weifang Goertek Electronics Co., Ltd",
    "102381": "Barrot Technology Co., Ltd.",
    "104E89": "Garmin International",
    "108286": "Luxshare Precision Industry Co., Ltd",
    "1082D7": "Realme Chongqing Mobile Telecommunications Corp., Ltd",
    "10C6FC": "Garmin International",
    "1423F2": "Broadcom",
    "143FA6": "Sony Home Entertainment & Sound Products",
    "146102": "Alps Alpine",
    "14907A": "Beijing Xiaomi Mobile Software Co., Ltd",
    "189552": "1MORE",
    "189578": "DENSO Corporation",
    "1C965A": "Weifang Goertek Electronics Co., Ltd",
    "207693": "Lenovo (Beijing) Co., Ltd.",
    "24ACAC": "Polar Electro Oy",
    "2811A5": "Bose Corporation",
    "2856C1": "Harman/Becker Automotive Systems GmbH",
    "2C27E4": "Luxshare Precision Industry Co., Ltd",
    "2C41A1": "Bose Corporation",
    "2CA7EF": "OnePlus Technology (Shenzhen) Co., Ltd",
    "305075": "GN Audio A/S (Jabra)",
    "30BB7D": "OnePlus Technology (Shenzhen) Co., Ltd",
    "347E5C": "Sonos, Inc.",
    "34885D": "Logitech",
    "38420B": "Sonos, Inc.",
    "38F32E": "Skullcandy",
    "3CCE15": "Mercedes-Benz USA, LLC",
    "3CCFB4": "Telink Semiconductor (Shanghai) Co., Ltd.",
    "405899": "Logitech",
    "406234": "Telink Semiconductor (Shanghai) Co., Ltd.",
    "4471B3": "Logitech",
    "4801C5": "OnePlus Technology (Shenzhen) Co., Ltd",
    "482335": "Dialog Semiconductor",
    "48C35A": "Lenovo (Beijing) Co., Ltd.",
    "4CFCAA": "Tesla, Inc.",
    "504A5E": "Masimo Corporation",
    "507C90": "Huami (Shenzhen) Information Technology Co., Ltd",
    "50C275": "GN Audio A/S (Jabra)",
    "5483BB": "Honda Motor Co., Ltd",
    "58A87B": "Fitbit, Inc.",
    "5C443E": "Skullcandy",
    "5C75AF": "Fitbit, Inc.",
    "60C5E6": "Skullcandy",
    "649C81": "Qualcomm Inc.",
    "6CCE44": "1MORE",
    "70879E": "Beken Corporation",
    "745E1C": "Pioneer Corporation",
    "806DDE": "Beken Corporation",
    "80EACA": "Dialog Semiconductor",
    "848A59": "Hisilicon Technologies Co., Ltd",
    "8809AF": "Masimo Corporation",
    "88124E": "Qualcomm Inc.",
    "8CFD15": "Imagine Marketing Private Limited (boAt)",
    "8CFDF0": "Qualcomm Inc.",
    "90E643": "Tesla, Inc.",
    "94B2CC": "Pioneer Corporation",
    "9C36F8": "Hyundai Kefico",
    "A038F8": "OURA Health Oy",
    "A09E1A": "Polar Electro Oy",
    "A43CD4": "JBL Professional",
    "A47EFA": "Withings",
    "AC44F2": "Yamaha Corporation",
    "C467B5": "Libratone A/S",
    "C8B6FE": "Fitbit, Inc.",
    "D47208": "Bragi GmbH",
    "D49C28": "JayBird LLC",
    "D834EE": "Shure Incorporated",
    "D8803C": "Anhui Huami Information Technology (Amazfit)",
    "F051EA": "Fitbit, Inc.",
    "F44EFD": "Actions Semiconductor Co., Ltd.",
    "F4C7AA": "Marvell Semiconductor, Inc.",
    "F4CE36": "Nordic Semiconductor ASA",
    "F4F3AA": "JBL GmbH & Co. KG",
    "FC934E": "Realtek Semiconductor Corp.",
}


# ---------------------------------------------------------------------------
# Address normalisation
# ---------------------------------------------------------------------------


def normalise_mac(mac: str) -> str:
    """Return ``AA:BB:CC:DD:EE:FF`` (uppercase, colon-separated), or ``""``.

    Accepts colon-, hyphen-, dot- or space-separated forms and bare 12-hex
    strings.  Returns the empty string for anything that is not a well-formed
    48-bit address — callers must treat ``""`` as "not a MAC", never as a
    zero address.
    """
    if not mac or not isinstance(mac, str):
        return ""
    compact = _MAC_SEP_RE.sub("", mac.strip()).upper()
    if not _HEX12_RE.match(compact):
        return ""
    return ":".join(compact[i : i + 2] for i in range(0, 12, 2))


def oui_prefix(mac: str) -> str:
    """Return the 24-bit OUI as 6 uppercase hex chars (``"AABBCC"``), or ``""``."""
    norm = normalise_mac(mac)
    if not norm:
        return ""
    return norm.replace(":", "")[:6]


def _first_octet(mac: str) -> Optional[int]:
    norm = normalise_mac(mac)
    if not norm:
        return None
    return int(norm[0:2], 16)


def is_locally_administered(mac: str) -> bool:
    """True if bit 1 of the first octet is set (locally administered address).

    Such an address was assigned by the local administrator / generated by the
    device, so it is not present in the IEEE registry at all and any OUI
    "match" against it is coincidental.
    """
    octet = _first_octet(mac)
    return octet is not None and bool(octet & 0x02)


def is_multicast(mac: str) -> bool:
    """True if bit 0 of the first octet is set (group/multicast address).

    Never valid as a Bluetooth device address; its presence indicates a parsing
    error or a corrupted record.
    """
    octet = _first_octet(mac)
    return octet is not None and bool(octet & 0x01)


def random_address_subtype(mac: str) -> str:
    """Classify a Bluetooth LE *random* address by its two most-significant bits.

    ``"static"``          — 0b11: random but stable for the peer's power cycle.
    ``"resolvable"``      — 0b01: Resolvable Private Address, rotates (~15 min).
    ``"non_resolvable"``  — 0b00: fully random, rotates.
    ``"reserved"``        — 0b10: not defined by the Core Spec.
    ``"invalid"``         — the input was not a MAC.

    None of these carry registry meaning; this function exists so the report can
    say *why* an OUI lookup was refused.
    """
    octet = _first_octet(mac)
    if octet is None:
        return "invalid"
    top = (octet >> 6) & 0x03
    return {0: "non_resolvable", 1: "resolvable", 2: "reserved", 3: "static"}[top]


# ---------------------------------------------------------------------------
# Lookup
# ---------------------------------------------------------------------------


def lookup_reason(mac: str, *, addr_type: Optional[int] = None) -> tuple[bool, str]:
    """Return ``(applicable, reason)`` for an OUI lookup on ``mac``.

    Exposed separately from :func:`lookup_vendor` so the report can print the
    *reason* a vendor field is blank instead of leaving the reader to guess.
    """
    norm = normalise_mac(mac)
    if not norm:
        return False, "not a valid 48-bit address"
    if norm == "00:00:00:00:00:00":
        return False, "all-zero address (controller address not yet read)"
    # AddrType 1 = random, 3 = random identity. Both are peer-generated values
    # with no IEEE registry meaning. Refusing here is the whole point.
    if addr_type in (1, 3):
        subtype = random_address_subtype(norm)
        return False, f"random address ({subtype}) — carries no IEEE OUI"
    if addr_type == 0xFF:
        return False, "anonymous address — carries no IEEE OUI"
    if is_multicast(norm):
        return False, "group/multicast bit set — not a valid device address"
    if is_locally_administered(norm):
        return False, "locally administered address — not in the IEEE registry"
    return True, "public address — IEEE MA-L lookup applicable"


def lookup_vendor(mac: str, *, addr_type: Optional[int] = None) -> Optional[str]:
    """Return the IEEE MA-L registered assignee for ``mac``, or ``None``.

    ``None`` is returned — deliberately, and without guessing — when:

    * ``addr_type`` is 1 (random) or 3 (random identity): the address was
      generated by the peer, so an OUI lookup would be a fabricated finding;
    * ``addr_type`` is 0xFF (anonymous);
    * the address is locally administered, multicast, all-zero or malformed;
    * the prefix is simply not in the pruned offline table.

    The distinction between those cases is available via :func:`lookup_reason`.
    """
    applicable, _reason = lookup_reason(mac, addr_type=addr_type)
    if not applicable:
        return None
    return OUI_TABLE.get(oui_prefix(mac))


def describe_vendor(mac: str, *, addr_type: Optional[int] = None) -> dict:
    """Full, self-documenting lookup result for embedding in a report row."""
    applicable, reason = lookup_reason(mac, addr_type=addr_type)
    vendor = OUI_TABLE.get(oui_prefix(mac)) if applicable else None
    return {
        "applicable": applicable,
        "reason": reason,
        "oui": oui_prefix(mac),
        "assignee": vendor,
        "registry": OUI_REGISTRY_NAME,
        "snapshot_date": OUI_REGISTRY_SNAPSHOT,
        # Phrasing matters: the assignee registered the address block. It is not
        # a claim about who manufactured or branded the product.
        "phrasing": (
            f"registered assignee of OUI {oui_prefix(mac)}" if vendor else ""
        ),
        "table_is_subset": True,
    }
