"""Automated Investigation Report assembler."""

from typing import Dict, Any, List


def generate_investigation_report(
    case_meta: Dict[str, Any], html_sections: List[str]
) -> str:
    """Generate a comprehensive HTML investigation report."""
    case_id = case_meta.get("case_id", "Unknown Case")

    report = [
        "<!DOCTYPE html>",
        "<html><head><title>Investigation Report</title>",
        "<style>body { font-family: sans-serif; line-height: 1.6; padding: 20px; }</style>",
        "</head><body>",
        f"<h1>Automated Investigation Report - Case {case_id}</h1>",
    ]

    for section in html_sections:
        report.append("<hr>")
        report.append(section)

    report.append("<hr><footer>Generated by Android Forensic Engine</footer>")
    report.append("</body></html>")
    return "\n".join(report)
